extern crate core;

use core::utils::error::Result as Result;

fn main() -> Result<()>{
    core::start()
}
